<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Company>Speaking In Bits</Company>
    <Product>Lecture Assistant</Product>
  </PropertyGroup>
</Project>
